m4_define(`_clearer', `Perhaps "$1" would be clearer than "$2".')
m4_define(`_closer', `Perhaps "$1" would be closer to your meaning than "$2".')
m4_define(`_comma', `There should be a comma after the word "$1" here.')
m4_define(`_typo', `"$1" looks like a typo. Did you mean "$2"?')
m4_define(`_replace', `Please use "$2" instead of "$1".')
m4_define(`_clarify', `Please clarify the meaning of "$1" here.')
m4_define(`_rephrase', `I think this needs rephrasing.')
m4_define(`_thirdPerson', `Please rephrase this into the third person.')
